### ISSUE TITLE
Put each return element on a separated line

### ISSUE THREAD

**Issue by pyvandenbussche** [gatemezing/QA4LOV#4]
e.g. http://lov.okfn.org/dataset/lov/qa?q=Who%20are%20the%20contributors%20of%20adms%3F

Each person in the result set should be separated with a new line similarly to http://lov.okfn.org/dataset/lov/qa?q=What%20are%20the%20versions%20of%20schema%3F

**Comment by gatemezing** [comment]
This is the result I get in my local setting for the first question. <img width="287" alt="capture d ecran 2016-06-16 17 40 36" src="https://cloud.githubusercontent.com/assets/922883/16122972/868d5d98-33e9-11e6-9cd2-bc7faf6f766e.png">
I wonder why it's different in prod..

**Comment by pyvandenbussche** [comment]
Offer a --html param
