### ISSUE TITLE
indication of type of result 

### ISSUE THREAD

**Issue by pyvandenbussche** [gatemezing/QA4LOV#6]
http://lov.okfn.org/dataset/lov/qa?q=What%20is%20prov%3F or http://lov.okfn.org/dataset/lov/qa?q=How%20many%20vocabularies%20reuse%20adms%3F returns a String for which nothing should be done for a better experience of the user.

for queries such as http://lov.okfn.org/dataset/lov/qa?q=Who%20publishes%20foaf%3F or http://lov.okfn.org/dataset/lov/qa?q=Who%20are%20the%20contributors%20of%20adms%3F is there a way to tell me that returned values are agents? In that case I could treat them differently and generate a link to thei webpage: http://lov.okfn.org/dataset/lov/agents/Dan%20Brickley

for queries such as http://lov.okfn.org/dataset/lov/qa?q=What%20are%20the%20versions%20of%20schema%3F or http://lov.okfn.org/dataset/lov/qa?q=What%20is%20the%20namespace%20of%20dcterms%3F similarly if you can tell me the answers are URI I can make them clickable.

**Comment by gatemezing** [comment]
Two categories:

1. Those with agents in the results **(02)**
     - Who publish [vocab] ? ----> returns agent.
     - Who are contributors of [vocab] ? ---> returns agent.
2. Those that can be made clickable because they return URL/URI **(04)**
     - What are the versions of [vocab]? ----> returns URL.
     - What are the languages of [vocab]? ----> returns URI.
     - Where to find [vocab] documentation? ----> returns URL.
     - What is the namespace of [vocab]? ----> returns URI

**Comment by pyvandenbussche** [comment]
Created various print handlers for the different types. with HTML output in option
